# Generated by Django 4.1.10 on 2023-08-19 10:54

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import trip_planning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='items/default.jpg', upload_to=trip_planning.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('index', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('categories', djongo.models.fields.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('adress', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('stars', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(max_length=30)),
                ('video', models.URLField(blank=True, null=True)),
                ('timetable', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('images', djongo.models.fields.ArrayField(model_container=trip_planning.models.ImagesItem)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlanning',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('item_list', djongo.models.fields.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
