# Generated by Django 4.1.10 on 2023-09-19 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sum_stars',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
