# Generated by Django 4.1.10 on 2023-09-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planning', '0003_item_sum_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplanning',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
