export const GET_ITEMS = 'GET_ITEMS';
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const GET_LIST_ITEMS = 'GET_LIST_ITEMS';
export const GET_ITEM = 'GET_ITEM';
export const GET_ITEMS_CONTENT = 'GET_ITEMS_CONTENT';
export const GET_ITEMS_COLLABORATIVE = 'GET_ITEMS_COLLABORATIVE';
export const GET_POPULAR_ITEMS = 'GET_POPULAR_ITEMS';
export const GET_ITEMS_WITH_CATEGORY = 'GET_ITEMS_WITH_CATEGORY ';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';

export const ADD_REVIEW = 'ADD_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS';
export const GET_REVIEWS_ITEM = 'GET_REVIEWS_ITEM';
export const STATISTIC_REVIEWS = 'STATISTIC_REVIEWS';
export const GET_NUMBERS_DASH = 'GET_NUMBERS_DASH';
export const REVIEWS_DISTRU = 'REVIEWS_DISTRU';
export const REVIEWS_TRIPS_NUMBERS = 'REVIEWS_TRIPS_NUMBERS';

export const GET_TRIPS = 'GET_TRIPS';
export const GET_TRIP = 'GET_TRIP';
export const RESET_ID_TRIP = 'RESET_ID_TRIP';
export const TRIPS_DISTRU = 'TRIPS_DISTRU';
export const LIKE_DISLIKE = 'LIKE_DISLIKE';
export const CREATE_TRIP = 'CREATE_TRIP';
export const SAVE_TRIP = 'SAVE_TRIP';
export const UPDATE_TRIP = 'UPDATE_TRIP';
export const DELETE_TRIP = 'DELETE_TRIP';
export const GET_COORDS = 'GET_COORDS';
export const SET_COORDS = 'SET_COORDS';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_USER_STAGE = 'REGISTER_USER_STAGE';
export const REGISTER_USER_SINGUP = 'REGISTER_USER_SINGUP';
export const REGISTER_USER_INFO = 'REGISTER_USER_INFO';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const KEY_WORD_USER = 'KEY_WORD_USER';
export const CATEGORIES_USER = 'CATEGORIES_USER';